name: PX68K Linux x86_64

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-px68k:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build libretro core with default CPU core
      run: |
       make -f Makefile.libretro clean
       make -f Makefile.libretro

  build-px68k-cpu-c68k:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build libretro core with updated C68K CPU core
      run: |
       make -f Makefile.libretro clean
       make -f Makefile.libretro C68K=1

  build-px68k-cpu-musashi:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build libretro core Musashi CPU core
      run: |
       make -f Makefile.libretro clean
       make -f Makefile.libretro MUSASHI=1
